const char* fileNames[] = {
    "samling/info/cpap.txt",
    "samling/info/bilevel.txt",
    "samling/info/vent.txt",
    "samling/info/inha.txt",
    "samling/info/syrgas.txt",
    "samling/info/puls.txt",
    "samling/info/komp.txt",
    "samling/info/slem.txt",
    "samling/info/and.txt",
    "samling/info/muskel.txt",
    "samling/info/nut.txt",
    "samling/info/infu.txt",
    "samling/info/koag.txt",
    "samling/info/apne.txt",
    "samling/info/tens.txt",
    "samling/info/ep.txt",
    "samling/info/ovrigt.txt"
};

const char* trNames = "samling/tr.txt";

const char* listFileName = "samling/meny.txt";

// ---- Tillbehör -----

const char* ctill[] = {
    "samling/cpap/c1.txt",
    "samling/cpap/c2.txt",
    "samling/cpap/c3.txt",
    "samling/cpap/c4.txt",
    "samling/cpap/c5.txt",
    "samling/cpap/c6.txt",
    "samling/cpap/c7.txt",
    "samling/cpap/c8.txt",
    "samling/cpap/c9.txt",
    "samling/cpap/c10.txt",
    "samling/cpap/c11.txt",
    "samling/cpap/c12.txt",
    "samling/cpap/c13.txt",
    "samling/cpap/c14.txt",
    "samling/cpap/c15.txt",
    "samling/cpap/c16.txt",
    "samling/cpap/c17.txt",
    "samling/cpap/c18.txt",
    "samling/cpap/c19.txt",
    "samling/cpap/c20.txt"
};

const char* bileveltill[] = {
    "samling/bilevel/b1.txt",
    "samling/bilevel/b2.txt",
    "samling/bilevel/b3.txt",
    "samling/bilevel/b4.txt",
    "samling/bilevel/b5.txt",
    "samling/bilevel/b6.txt",
    "samling/bilevel/b7.txt",
    "samling/bilevel/b8.txt",
    "samling/bilevel/b9.txt",
    "samling/bilevel/b10.txt",
    "samling/bilevel/b11.txt",
    "samling/bilevel/b12.txt",
    "samling/bilevel/b13.txt",
    "samling/bilevel/b14.txt",
    "samling/bilevel/b15.txt",
    "samling/bilevel/b16.txt",
    "samling/bilevel/b17.txt",
    "samling/bilevel/b18.txt",
    "samling/bilevel/b19.txt",
    "samling/bilevel/b20.txt"
};

const char* vtill[] = {
    "samling/vent/v1.txt",
    "samling/vent/v2.txt",
    "samling/vent/v3.txt",
    "samling/vent/v4.txt",
    "samling/vent/v5.txt",
    "samling/vent/v6.txt",
    "samling/vent/v7.txt",
    "samling/vent/v8.txt",
    "samling/vent/v9.txt",
    "samling/vent/v10.txt",
    "samling/vent/v11.txt",
    "samling/vent/v12.txt",
    "samling/vent/v13.txt",
    "samling/vent/v14.txt",
    "samling/vent/v15.txt",
    "samling/vent/v16.txt",
    "samling/vent/v17.txt",
    "samling/vent/v18.txt",
    "samling/vent/v19.txt",
    "samling/vent/v20.txt"
};

const char* inhatill[] = {
    "samling/inha/inh1.txt",
    "samling/inha/inh2.txt",
    "samling/inha/inh3.txt",
    "samling/inha/inh4.txt",
    "samling/inha/inh5.txt",
    "samling/inha/inh6.txt",
    "samling/inha/inh7.txt",
    "samling/inha/inh8.txt",
    "samling/inha/inh9.txt",
    "samling/inha/inh10.txt",
    "samling/inha/inh11.txt",
    "samling/inha/inh12.txt",
    "samling/inha/inh13.txt",
    "samling/inha/inh14.txt",
    "samling/inha/inh15.txt",
    "samling/inha/inh16.txt",
    "samling/inha/inh17.txt",
    "samling/inha/inh18.txt",
    "samling/inha/inh19.txt",
    "samling/inha/inh20.txt"
};

const char* syrgastill[] = {
    "samling/syrgas/syr1.txt",
    "samling/syrgas/syr2.txt",
    "samling/syrgas/syr3.txt",
    "samling/syrgas/syr4.txt",
    "samling/syrgas/syr5.txt",
    "samling/syrgas/syr6.txt",
    "samling/syrgas/syr7.txt",
    "samling/syrgas/syr8.txt",
    "samling/syrgas/syr9.txt",
    "samling/syrgas/syr10.txt",
    "samling/syrgas/syr11.txt",
    "samling/syrgas/syr12.txt",
    "samling/syrgas/syr13.txt",
    "samling/syrgas/syr14.txt",
    "samling/syrgas/syr15.txt",
    "samling/syrgas/syr16.txt",
    "samling/syrgas/syr17.txt",
    "samling/syrgas/syr18.txt",
    "samling/syrgas/syr19.txt",
    "samling/syrgas/syr20.txt"
};

const char* pulstill[] = {
    "samling/puls/puls1.txt",
    "samling/puls/puls2.txt",
    "samling/puls/puls3.txt",
    "samling/puls/puls4.txt",
    "samling/puls/puls5.txt",
    "samling/puls/puls6.txt",
    "samling/puls/puls7.txt",
    "samling/puls/puls8.txt",
    "samling/puls/puls9.txt",
    "samling/puls/puls10.txt",
    "samling/puls/puls11.txt",
    "samling/puls/puls12.txt",
    "samling/puls/puls13.txt",
    "samling/puls/puls14.txt",
    "samling/puls/puls15.txt",
    "samling/puls/puls16.txt",
    "samling/puls/puls17.txt",
    "samling/puls/puls18.txt",
    "samling/puls/puls19.txt",
    "samling/puls/puls20.txt"
};

const char* komptill[] = {
    "samling/komp/komp1.txt",
    "samling/komp/komp2.txt",
    "samling/komp/komp3.txt",
    "samling/komp/komp4.txt",
    "samling/komp/komp5.txt",
    "samling/komp/komp6.txt",
    "samling/komp/komp7.txt",
    "samling/komp/komp8.txt",
    "samling/komp/komp9.txt",
    "samling/komp/komp10.txt",
    "samling/komp/komp11.txt",
    "samling/komp/komp12.txt",
    "samling/komp/komp13.txt",
    "samling/komp/komp14.txt",
    "samling/komp/komp15.txt",
    "samling/komp/komp16.txt",
    "samling/komp/komp17.txt",
    "samling/komp/komp18.txt",
    "samling/komp/komp19.txt",
    "samling/komp/komp20.txt"
};

const char* slemtill[] = {
    "samling/slem/slem1.txt",
    "samling/slem/slem2.txt",
    "samling/slem/slem3.txt",
    "samling/slem/slem4.txt",
    "samling/slem/slem5.txt",
    "samling/slem/slem6.txt",
    "samling/slem/slem7.txt",
    "samling/slem/slem8.txt",
    "samling/slem/slem9.txt",
    "samling/slem/slem10.txt",
    "samling/slem/slem11.txt",
    "samling/slem/slem12.txt",
    "samling/slem/slem13.txt",
    "samling/slem/slem14.txt",
    "samling/slem/slem15.txt",
    "samling/slem/slem16.txt",
    "samling/slem/slem17.txt",
    "samling/slem/slem18.txt",
    "samling/slem/slem19.txt",
    "samling/slem/slem20.txt"
};

const char* andtill[] = {
    "samling/and/and1.txt",
    "samling/and/and2.txt",
    "samling/and/and3.txt",
    "samling/and/and4.txt",
    "samling/and/and5.txt",
    "samling/and/and6.txt",
    "samling/and/and7.txt",
    "samling/and/and8.txt",
    "samling/and/and9.txt",
    "samling/and/and10.txt",
    "samling/and/and11.txt",
    "samling/and/and12.txt",
    "samling/and/and13.txt",
    "samling/and/and14.txt",
    "samling/and/and15.txt",
    "samling/and/and16.txt",
    "samling/and/and17.txt",
    "samling/and/and18.txt",
    "samling/and/and19.txt",
    "samling/and/and20.txt"
};

const char* muskeltill[] = {
    "samling/muskel/muskel1.txt",
    "samling/muskel/muskel2.txt",
    "samling/muskel/muskel3.txt",
    "samling/muskel/muskel4.txt",
    "samling/muskel/muskel5.txt",
    "samling/muskel/muskel6.txt",
    "samling/muskel/muskel7.txt",
    "samling/muskel/muskel8.txt",
    "samling/muskel/muskel9.txt",
    "samling/muskel/muskel10.txt",
    "samling/muskel/muskel11.txt",
    "samling/muskel/muskel12.txt",
    "samling/muskel/muskel13.txt",
    "samling/muskel/muskel14.txt",
    "samling/muskel/muskel15.txt",
    "samling/muskel/muskel16.txt",
    "samling/muskel/muskel17.txt",
    "samling/muskel/muskel18.txt",
    "samling/muskel/muskel19.txt",
    "samling/muskel/muskel20.txt"
};

const char* nuttill[] = {
    "samling/nut/nut1.txt",
    "samling/nut/nut2.txt",
    "samling/nut/nut3.txt",
    "samling/nut/nut4.txt",
    "samling/nut/nut5.txt",
    "samling/nut/nut6.txt",
    "samling/nut/nut7.txt",
    "samling/nut/nut8.txt",
    "samling/nut/nut9.txt",
    "samling/nut/nut10.txt",
    "samling/nut/nut11.txt",
    "samling/nut/nut12.txt",
    "samling/nut/nut13.txt",
    "samling/nut/nut14.txt",
    "samling/nut/nut15.txt",
    "samling/nut/nut16.txt",
    "samling/nut/nut17.txt",
    "samling/nut/nut18.txt",
    "samling/nut/nut19.txt",
    "samling/nut/nut20.txt"
};

const char* infutill[] = {
    "samling/infu/infu1.txt",
    "samling/infu/infu2.txt",
    "samling/infu/infu3.txt",
    "samling/infu/infu4.txt",
    "samling/infu/infu5.txt",
    "samling/infu/infu6.txt",
    "samling/infu/infu7.txt",
    "samling/infu/infu8.txt",
    "samling/infu/infu9.txt",
    "samling/infu/infu10.txt",
    "samling/infu/infu11.txt",
    "samling/infu/infu12.txt",
    "samling/infu/infu13.txt",
    "samling/infu/infu14.txt",
    "samling/infu/infu15.txt",
    "samling/infu/infu16.txt",
    "samling/infu/infu17.txt",
    "samling/infu/infu18.txt",
    "samling/infu/infu19.txt",
    "samling/infu/infu20.txt"
};

const char* koagtill[] = {
    "samling/koag/koag1.txt",
    "samling/koag/koag2.txt",
    "samling/koag/koag3.txt",
    "samling/koag/koag4.txt",
    "samling/koag/koag5.txt",
    "samling/koag/koag6.txt",
    "samling/koag/koag7.txt",
    "samling/koag/koag8.txt",
    "samling/koag/koag9.txt",
    "samling/koag/koag10.txt",
    "samling/koag/koag11.txt",
    "samling/koag/koag12.txt",
    "samling/koag/koag13.txt",
    "samling/koag/koag14.txt",
    "samling/koag/koag15.txt",
    "samling/koag/koag16.txt",
    "samling/koag/koag17.txt",
    "samling/koag/koag18.txt",
    "samling/koag/koag19.txt",
    "samling/koag/koag20.txt"
};

const char* apnetill[] = {
    "samling/apne/apne1.txt",
    "samling/apne/apne2.txt",
    "samling/apne/apne3.txt",
    "samling/apne/apne4.txt",
    "samling/apne/apne5.txt",
    "samling/apne/apne6.txt",
    "samling/apne/apne7.txt",
    "samling/apne/apne8.txt",
    "samling/apne/apne9.txt",
    "samling/apne/apne10.txt",
    "samling/apne/apne11.txt",
    "samling/apne/apne12.txt",
    "samling/apne/apne13.txt",
    "samling/apne/apne14.txt",
    "samling/apne/apne15.txt",
    "samling/apne/apne16.txt",
    "samling/apne/apne17.txt",
    "samling/apne/apne18.txt",
    "samling/apne/apne19.txt",
    "samling/apne/apne20.txt"
};

const char* tenstill[] = {
    "samling/tens/tens1.txt",
    "samling/tens/tens2.txt",
    "samling/tens/tens3.txt",
    "samling/tens/tens4.txt",
    "samling/tens/tens5.txt",
    "samling/tens/tens6.txt",
    "samling/tens/tens7.txt",
    "samling/tens/tens8.txt",
    "samling/tens/tens9.txt",
    "samling/tens/tens10.txt",
    "samling/tens/tens11.txt",
    "samling/tens/tens12.txt",
    "samling/tens/tens13.txt",
    "samling/tens/tens14.txt",
    "samling/tens/tens15.txt",
    "samling/tens/tens16.txt",
    "samling/tens/tens17.txt",
    "samling/tens/tens18.txt",
    "samling/tens/tens19.txt",
    "samling/tens/tens20.txt"
};

const char* eptill[] = {
    "samling/ep/ep1.txt",
    "samling/ep/ep2.txt",
    "samling/ep/ep3.txt",
    "samling/ep/ep4.txt",
    "samling/ep/ep5.txt",
    "samling/ep/ep6.txt",
    "samling/ep/ep7.txt",
    "samling/ep/ep8.txt",
    "samling/ep/ep9.txt",
    "samling/ep/ep10.txt",
    "samling/ep/ep11.txt",
    "samling/ep/ep12.txt",
    "samling/ep/ep13.txt",
    "samling/ep/ep14.txt",
    "samling/ep/ep15.txt",
    "samling/ep/ep16.txt",
    "samling/ep/ep17.txt",
    "samling/ep/ep18.txt",
    "samling/ep/ep19.txt",
    "samling/ep/ep20.txt"
};

const char* ovrigttill[] = {
    "samling/ovrigt/o1.txt",
    "samling/ovrigt/o2.txt",
    "samling/ovrigt/o3.txt",
    "samling/ovrigt/o4.txt",
    "samling/ovrigt/o5.txt",
    "samling/ovrigt/o6.txt",
    "samling/ovrigt/o7.txt",
    "samling/ovrigt/o8.txt",
    "samling/ovrigt/o9.txt",
    "samling/ovrigt/o10.txt",
    "samling/ovrigt/o11.txt",
    "samling/ovrigt/o12.txt",
    "samling/ovrigt/o13.txt",
    "samling/ovrigt/o14.txt",
    "samling/ovrigt/o15.txt",
    "samling/ovrigt/o16.txt",
    "samling/ovrigt/o17.txt",
    "samling/ovrigt/o18.txt",
    "samling/ovrigt/o19.txt",
    "samling/ovrigt/o20.txt"
};



// ---- Reservdelar -----

const char* creserv[] = {
    "samling/cpap/c111.txt",
    "samling/cpap/c122.txt",
    "samling/cpap/c133.txt",
    "samling/cpap/c144.txt",
    "samling/cpap/c155.txt",
    "samling/cpap/c166.txt",
    "samling/cpap/c177.txt",
    "samling/cpap/c188.txt",
    "samling/cpap/c199.txt",
    "samling/cpap/c100.txt",
    "samling/cpap/c110.txt",
    "samling/cpap/c120.txt",
    "samling/cpap/c130.txt",
    "samling/cpap/c140.txt",
    "samling/cpap/c150.txt",
    "samling/cpap/c160.txt",
    "samling/cpap/c170.txt",
    "samling/cpap/c180.txt",
    "samling/cpap/c190.txt",
    "samling/cpap/c200.txt"
};

const char* bilevelreserv[] = {
    "samling/bilevel/b111.txt",
    "samling/bilevel/b122.txt",
    "samling/bilevel/b133.txt",
    "samling/bilevel/b144.txt",
    "samling/bilevel/b155.txt",
    "samling/bilevel/b166.txt",
    "samling/bilevel/b177.txt",
    "samling/bilevel/b188.txt",
    "samling/bilevel/b199.txt",
    "samling/bilevel/b100.txt",
    "samling/bilevel/b110.txt",
    "samling/bilevel/b120.txt",
    "samling/bilevel/b130.txt",
    "samling/bilevel/b140.txt",
    "samling/bilevel/b150.txt",
    "samling/bilevel/b160.txt",
    "samling/bilevel/b170.txt",
    "samling/bilevel/b180.txt",
    "samling/bilevel/b190.txt",
    "samling/bilevel/b200.txt"
};

const char* vreserv[] = {
    "samling/vent/v111.txt",
    "samling/vent/v122.txt",
    "samling/vent/v133.txt",
    "samling/vent/v144.txt",
    "samling/vent/v155.txt",
    "samling/vent/v166.txt",
    "samling/vent/v177.txt",
    "samling/vent/v188.txt",
    "samling/vent/v199.txt",
    "samling/vent/v100.txt",
    "samling/vent/v110.txt",
    "samling/vent/v120.txt",
    "samling/vent/v130.txt",
    "samling/vent/v140.txt",
    "samling/vent/v150.txt",
    "samling/vent/v160.txt",
    "samling/vent/v170.txt",
    "samling/vent/v180.txt",
    "samling/vent/v190.txt",
    "samling/vent/v200.txt"
};

const char* inhareserv[] = {
    "samling/inha/inh111.txt",
    "samling/inha/inh122.txt",
    "samling/inha/inh133.txt",
    "samling/inha/inh144.txt",
    "samling/inha/inh155.txt",
    "samling/inha/inh166.txt",
    "samling/inha/inh177.txt",
    "samling/inha/inh188.txt",
    "samling/inha/inh199.txt",
    "samling/inha/inh100.txt",
    "samling/inha/inh110.txt",
    "samling/inha/inh120.txt",
    "samling/inha/inh130.txt",
    "samling/inha/inh140.txt",
    "samling/inha/inh150.txt",
    "samling/inha/inh160.txt",
    "samling/inha/inh170.txt",
    "samling/inha/inh180.txt",
    "samling/inha/inh190.txt",
    "samling/inha/inh200.txt"
};

const char* syrgasreserv[] = {
    "samling/syrgas/syr111.txt",
    "samling/syrgas/syr122.txt",
    "samling/syrgas/syr133.txt",
    "samling/syrgas/syr144.txt",
    "samling/syrgas/syr155.txt",
    "samling/syrgas/syr166.txt",
    "samling/syrgas/syr177.txt",
    "samling/syrgas/syr188.txt",
    "samling/syrgas/syr199.txt",
    "samling/syrgas/syr100.txt",
    "samling/syrgas/syr110.txt",
    "samling/syrgas/syr120.txt",
    "samling/syrgas/syr130.txt",
    "samling/syrgas/syr140.txt",
    "samling/syrgas/syr150.txt",
    "samling/syrgas/syr160.txt",
    "samling/syrgas/syr170.txt",
    "samling/syrgas/syr180.txt",
    "samling/syrgas/syr190.txt",
    "samling/syrgas/syr200.txt"
};

const char* pulsreserv[] = {
    "samling/puls/puls111.txt",
    "samling/puls/puls122.txt",
    "samling/puls/puls133.txt",
    "samling/puls/puls144.txt",
    "samling/puls/puls155.txt",
    "samling/puls/puls166.txt",
    "samling/puls/puls177.txt",
    "samling/puls/puls188.txt",
    "samling/puls/puls199.txt",
    "samling/puls/puls100.txt",
    "samling/puls/puls110.txt",
    "samling/puls/puls120.txt",
    "samling/puls/puls130.txt",
    "samling/puls/puls140.txt",
    "samling/puls/puls150.txt",
    "samling/puls/puls160.txt",
    "samling/puls/puls170.txt",
    "samling/puls/puls180.txt",
    "samling/puls/puls190.txt",
    "samling/puls/puls200.txt"
};

const char* kompreserv[] = {
    "samling/komp/komp111.txt",
    "samling/komp/komp122.txt",
    "samling/komp/komp133.txt",
    "samling/komp/komp144.txt",
    "samling/komp/komp155.txt",
    "samling/komp/komp166.txt",
    "samling/komp/komp177.txt",
    "samling/komp/komp188.txt",
    "samling/komp/komp199.txt",
    "samling/komp/komp100.txt",
    "samling/komp/komp110.txt",
    "samling/komp/komp120.txt",
    "samling/komp/komp130.txt",
    "samling/komp/komp140.txt",
    "samling/komp/komp150.txt",
    "samling/komp/komp160.txt",
    "samling/komp/komp170.txt",
    "samling/komp/komp180.txt",
    "samling/komp/komp190.txt",
    "samling/komp/komp200.txt"
};

const char* slemreserv[] = {
    "samling/slem/slem111.txt",
    "samling/slem/slem122.txt",
    "samling/slem/slem133.txt",
    "samling/slem/slem144.txt",
    "samling/slem/slem155.txt",
    "samling/slem/slem166.txt",
    "samling/slem/slem177.txt",
    "samling/slem/slem188.txt",
    "samling/slem/slem199.txt",
    "samling/slem/slem100.txt",
    "samling/slem/slem110.txt",
    "samling/slem/slem120.txt",
    "samling/slem/slem130.txt",
    "samling/slem/slem140.txt",
    "samling/slem/slem150.txt",
    "samling/slem/slem160.txt",
    "samling/slem/slem170.txt",
    "samling/slem/slem180.txt",
    "samling/slem/slem190.txt",
    "samling/slem/slem200.txt"
};

const char* andreserv[] = {
    "samling/and/and111.txt",
    "samling/and/and122.txt",
    "samling/and/and133.txt",
    "samling/and/and144.txt",
    "samling/and/and155.txt",
    "samling/and/and166.txt",
    "samling/and/and177.txt",
    "samling/and/and188.txt",
    "samling/and/and199.txt",
    "samling/and/and100.txt",
    "samling/and/and110.txt",
    "samling/and/and120.txt",
    "samling/and/and130.txt",
    "samling/and/and140.txt",
    "samling/and/and150.txt",
    "samling/and/and160.txt",
    "samling/and/and170.txt",
    "samling/and/and180.txt",
    "samling/and/and190.txt",
    "samling/and/and200.txt"
};

const char* muskelreserv[] = {
    "samling/muskel/muskel111.txt",
    "samling/muskel/muskel122.txt",
    "samling/muskel/muskel133.txt",
    "samling/muskel/muskel144.txt",
    "samling/muskel/muskel155.txt",
    "samling/muskel/muskel166.txt",
    "samling/muskel/muskel177.txt",
    "samling/muskel/muskel188.txt",
    "samling/muskel/muskel199.txt",
    "samling/muskel/muskel100.txt",
    "samling/muskel/muskel110.txt",
    "samling/muskel/muskel120.txt",
    "samling/muskel/muskel130.txt",
    "samling/muskel/muskel140.txt",
    "samling/muskel/muskel150.txt",
    "samling/muskel/muskel160.txt",
    "samling/muskel/muskel170.txt",
    "samling/muskel/muskel180.txt",
    "samling/muskel/muskel190.txt",
    "samling/muskel/muskel200.txt"
};

const char* nutreserv[] = {
    "samling/nut/nut111.txt",
    "samling/nut/nut122.txt",
    "samling/nut/nut133.txt",
    "samling/nut/nut144.txt",
    "samling/nut/nut155.txt",
    "samling/nut/nut166.txt",
    "samling/nut/nut177.txt",
    "samling/nut/nut188.txt",
    "samling/nut/nut199.txt",
    "samling/nut/nut100.txt",
    "samling/nut/nut110.txt",
    "samling/nut/nut120.txt",
    "samling/nut/nut130.txt",
    "samling/nut/nut140.txt",
    "samling/nut/nut150.txt",
    "samling/nut/nut160.txt",
    "samling/nut/nut170.txt",
    "samling/nut/nut180.txt",
    "samling/nut/nut190.txt",
    "samling/nut/nut200.txt"
};

const char* infureserv[] = {
    "samling/infu/infu111.txt",
    "samling/infu/infu122.txt",
    "samling/infu/infu133.txt",
    "samling/infu/infu144.txt",
    "samling/infu/infu155.txt",
    "samling/infu/infu166.txt",
    "samling/infu/infu177.txt",
    "samling/infu/infu188.txt",
    "samling/infu/infu199.txt",
    "samling/infu/infu100.txt",
    "samling/infu/infu110.txt",
    "samling/infu/infu120.txt",
    "samling/infu/infu130.txt",
    "samling/infu/infu140.txt",
    "samling/infu/infu150.txt",
    "samling/infu/infu160.txt",
    "samling/infu/infu170.txt",
    "samling/infu/infu180.txt",
    "samling/infu/infu190.txt",
    "samling/infu/infu200.txt"
};

const char* koagreserv[] = {
    "samling/koag/koag111.txt",
    "samling/koag/koag122.txt",
    "samling/koag/koag133.txt",
    "samling/koag/koag144.txt",
    "samling/koag/koag155.txt",
    "samling/koag/koag166.txt",
    "samling/koag/koag177.txt",
    "samling/koag/koag188.txt",
    "samling/koag/koag199.txt",
    "samling/koag/koag100.txt",
    "samling/koag/koag110.txt",
    "samling/koag/koag120.txt",
    "samling/koag/koag130.txt",
    "samling/koag/koag140.txt",
    "samling/koag/koag150.txt",
    "samling/koag/koag160.txt",
    "samling/koag/koag170.txt",
    "samling/koag/koag180.txt",
    "samling/koag/koag190.txt",
    "samling/koag/koag200.txt"
};

const char* apnereserv[] = {
    "samling/apne/apne111.txt",
    "samling/apne/apne122.txt",
    "samling/apne/apne133.txt",
    "samling/apne/apne144.txt",
    "samling/apne/apne155.txt",
    "samling/apne/apne166.txt",
    "samling/apne/apne177.txt",
    "samling/apne/apne188.txt",
    "samling/apne/apne199.txt",
    "samling/apne/apne100.txt",
    "samling/apne/apne110.txt",
    "samling/apne/apne120.txt",
    "samling/apne/apne130.txt",
    "samling/apne/apne140.txt",
    "samling/apne/apne150.txt",
    "samling/apne/apne160.txt",
    "samling/apne/apne170.txt",
    "samling/apne/apne180.txt",
    "samling/apne/apne190.txt",
    "samling/apne/apne200.txt"
};

const char* tensreserv[] = {
    "samling/tens/tens111.txt",
    "samling/tens/tens122.txt",
    "samling/tens/tens133.txt",
    "samling/tens/tens144.txt",
    "samling/tens/tens155.txt",
    "samling/tens/tens166.txt",
    "samling/tens/tens177.txt",
    "samling/tens/tens188.txt",
    "samling/tens/tens199.txt",
    "samling/tens/tens100.txt",
    "samling/tens/tens110.txt",
    "samling/tens/tens120.txt",
    "samling/tens/tens130.txt",
    "samling/tens/tens140.txt",
    "samling/tens/tens150.txt",
    "samling/tens/tens160.txt",
    "samling/tens/tens170.txt",
    "samling/tens/tens180.txt",
    "samling/tens/tens190.txt",
    "samling/tens/tens200.txt"
};

const char* epreserv[] = {
    "samling/ep/ep111.txt",
    "samling/ep/ep122.txt",
    "samling/ep/ep133.txt",
    "samling/ep/ep144.txt",
    "samling/ep/ep155.txt",
    "samling/ep/ep166.txt",
    "samling/ep/ep177.txt",
    "samling/ep/ep188.txt",
    "samling/ep/ep199.txt",
    "samling/ep/ep100.txt",
    "samling/ep/ep110.txt",
    "samling/ep/ep120.txt",
    "samling/ep/ep130.txt",
    "samling/ep/ep140.txt",
    "samling/ep/ep150.txt",
    "samling/ep/ep160.txt",
    "samling/ep/ep170.txt",
    "samling/ep/ep180.txt",
    "samling/ep/ep190.txt",
    "samling/ep/ep200.txt"
};

const char* ovrigtreserv[] = {
    "samling/ovrigt/o111.txt",
    "samling/ovrigt/o122.txt",
    "samling/ovrigt/o133.txt",
    "samling/ovrigt/o144.txt",
    "samling/ovrigt/o155.txt",
    "samling/ovrigt/o166.txt",
    "samling/ovrigt/o177.txt",
    "samling/ovrigt/o188.txt",
    "samling/ovrigt/o199.txt",
    "samling/ovrigt/o100.txt",
    "samling/ovrigt/o110.txt",
    "samling/ovrigt/o120.txt",
    "samling/ovrigt/o130.txt",
    "samling/ovrigt/o140.txt",
    "samling/ovrigt/o150.txt",
    "samling/ovrigt/o160.txt",
    "samling/ovrigt/o170.txt",
    "samling/ovrigt/o180.txt",
    "samling/ovrigt/o190.txt",
    "samling/ovrigt/o200.txt"
};

// ---- Listor till Tb och Rd ----

const char** listTill[] = {
    ctill,
    bileveltill,
    vtill,
    inhatill,
    syrgastill,
    pulstill,
    komptill,
    slemtill,
    andtill,
    muskeltill,
    nuttill,
    infutill,
    koagtill,
    apnetill,
    tenstill,
    eptill,
    ovrigttill
};

const char** listReserv[] = {
    creserv,
    bilevelreserv,
    vreserv,
    inhareserv,
    syrgasreserv,
    pulsreserv,
    kompreserv,
    slemreserv,
    andreserv,
    muskelreserv,
    nutreserv,
    infureserv,
    koagreserv,
    apnereserv,
    tensreserv,
    epreserv,
    ovrigtreserv
};

